variables:
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    SLSA_PROVENANCE_SCHEMA_VERSION: "v1"

stages:
    - lint
    - build
    - test

image: golang:1

govet:
    stage: lint
    script:
        - go vet *.go

build:
    stage: build
    script:
        - go build name2mtime.go
    artifacts:
        paths:
            - ./name2mtime
        expire_in: "1 month"

test:
    stage: test
    script:
        - go test name2mtime_test.go
